// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDesD1X0-CuByW0ZpkWT0fd76xjQ2fOuVA',
    appId: '1:217754005940:web:55ee54b97319f9598dc2e1',
    messagingSenderId: '217754005940',
    projectId: 'flutter-firebase-cdea8',
    authDomain: 'flutter-firebase-cdea8.firebaseapp.com',
    storageBucket: 'flutter-firebase-cdea8.appspot.com',
    measurementId: 'G-VSJ0FDV6BD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXuTnBJ2yntuOdE704cJGb4tfy-e-tRVQ',
    appId: '1:217754005940:android:4899be11a1ddb1a98dc2e1',
    messagingSenderId: '217754005940',
    projectId: 'flutter-firebase-cdea8',
    storageBucket: 'flutter-firebase-cdea8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_HCEmS_8tFz2zsJPUB6zLgowiDrtzXv0',
    appId: '1:217754005940:ios:9dbe261c0a8b581c8dc2e1',
    messagingSenderId: '217754005940',
    projectId: 'flutter-firebase-cdea8',
    storageBucket: 'flutter-firebase-cdea8.appspot.com',
    iosClientId: '217754005940-2p19jd25hqaoo5apl8uuuv5blh7b9na5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_HCEmS_8tFz2zsJPUB6zLgowiDrtzXv0',
    appId: '1:217754005940:ios:9dbe261c0a8b581c8dc2e1',
    messagingSenderId: '217754005940',
    projectId: 'flutter-firebase-cdea8',
    storageBucket: 'flutter-firebase-cdea8.appspot.com',
    iosClientId: '217754005940-2p19jd25hqaoo5apl8uuuv5blh7b9na5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
